# Generated by Django 6.0.5 on 2026-08-24 07:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الموبايل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_type', models.CharField(max_length=50, unique=True, verbose_name='نوع الشجرة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شجرة',
                'verbose_name_plural': 'الأشجار',
                'ordering': ['tree_type'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البيع')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الوزن بالكيلو')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=2.5, max_digits=10, verbose_name='سعر الكيلو')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='إجمالي المبيعات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.participant', verbose_name='المشارك')),
            ],
            options={
                'verbose_name': 'بيع',
                'verbose_name_plural': 'المبيعات',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='العدد')),
                ('price_per_tree', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الشجرة')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tree')),
            ],
            options={
                'verbose_name': 'شجرة في البيع',
                'verbose_name_plural': 'الأشجار في البيع',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='trees_purchased',
            field=models.ManyToManyField(through='core.SaleTree', to='core.tree', verbose_name='الأشجار المشتراة'),
        ),
        migrations.CreateModel(
            name='TreeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='العدد')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='رقم الدور')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant', verbose_name='المشارك')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tree', verbose_name='نوع الشجرة')),
            ],
            options={
                'verbose_name': 'طلب شجرة',
                'verbose_name_plural': 'طلبات الأشجار',
                'ordering': ['position', 'request_date'],
            },
        ),
    ]
