# Generated by Django 6.0.5 on 2026-08-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
