# Generated by Django 6.0.5 on 2026-09-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_treerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المصروف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع مصروف',
                'verbose_name_plural': 'أنواع المصروفات',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الموبايل'),
        ),
        migrations.CreateModel(
            name='SaleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='العدد')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الوحدة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensecategory', verbose_name='نوع المصروف')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale')),
            ],
            options={
                'verbose_name': 'مصروف بيع',
                'verbose_name_plural': 'مصروفات البيع',
            },
        ),
    ]
