# Generated by Django 6.0.5 on 2026-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expensecategory_alter_participant_phone_saleexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='treerequest',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم التسليم'),
        ),
        migrations.AddField(
            model_name='treerequest',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشراء'),
        ),
        migrations.AddField(
            model_name='treerequest',
            name='ready_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التجهيز'),
        ),
        migrations.AlterField(
            model_name='treerequest',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AlterField(
            model_name='treerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('purchased', 'تم الشراء'), ('ready', 'جاهز للتسليم'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
